### ISSUE TITLE
Dense materials requires lectures

### ISSUE THREAD

**Issue by cliffweitzman** [MakeSchool-Tutorials/Makestagram-Swift-V2#22] opened 2016-06-15 04:24 UTC
The bottom part of section 8 of Makestagram part one - particularly on closures will requires lecture or should have one more separation specifically since the swift intro doc does not include any information on closures and what they are.

**Comment by dionlarson** [comment] 2016-06-19 08:23
Closing since this is a dupe of #14

**Closed as completed by dionlarson** 2016-06-19 08:23 UTC
Labels: enhancement
